JdbcRepository
Good1dea/A-level pull request #20
Opened 2023-02-02 02:17 UTC by Good1dea

2023-02-03 22:33 UTC, Fabolo12 requested changes

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/model/Order.java
> +    private final String date;
Это должна была быть именно дата

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +    private static final String[] createTablesSQL = {"CREATE TABLE IF NOT EXISTS engines (idEngine VARCHAR(255) " +
На каждую модель должен быть свой репозиторий

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                    "\' , \'" + order.getDate() + " \' )";
Это SQL инъекция...

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +            savePassOrTruckCar.execute();
Тут нет транзации

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                "FULL OUTER JOIN engines ON cars.engineID = engines.idEngine " +
А почему такой джоин?

2023-02-03 22:33 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                "DELETE FROM engines WHERE idengine not IN (SELECT engineid FROM cars)";
При удалении ордера почему-то удаляется только двигатель еще

2023-02-04 14:06 UTC, Good1dea commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                "FULL OUTER JOIN engines ON cars.engineID = engines.idEngine " +
Потому что нам нужна вся информация, чтобы воссоздать все машины (и пассажирские, и грузовые, и с двигателями), занесенные в базу ранее.

2023-02-04 14:09 UTC, Good1dea commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                "DELETE FROM engines WHERE idengine not IN (SELECT engineid FROM cars)";
При удалении ордера машины удаляются каскадно

2023-02-04 23:00 UTC, Fabolo12 commented on src/main/java/com/sydoruk/repository/JdbcRepository.java
> +                "FULL OUTER JOIN engines ON cars.engineID = engines.idEngine " +
Да, но ты же достаешь вообще все данные

2023-02-04 23:01 UTC, Fabolo12 approved these changes

2023-02-07 21:46 UTC, merged